/**
 * ShadowStream AdShield — single owner of the global `window.open` override.
 *
 * Before this module there were two independent overrides fighting each other:
 *   1. an inline <script> in public/index.html that allow-listed by substring
 *   2. a useEffect in ShadowStreamPlayer.js that blocked *everything*
 * Whichever mounted last won, and the component's version also swallowed the
 * app's own navigation. This is the only place that touches window.open.
 *
 * Policy: third-party embed providers routinely try to open ad/popunder tabs.
 * We block those. We never block navigation the user actually initiated, and we
 * never block our own first-party origins.
 */

/** Origins we own. Anything on these is allowed to open a window. */
const FIRST_PARTY = [
    'ssmoviestvs.site',
    'streamapp.muhd-faisal-work.workers.dev',
    'frontend.muhd-faisal-work.workers.dev',
    'streamapp-catalog.muhd-faisal-work.workers.dev',
    'space.minimax.io',
    'localhost',
];

/** Host fragments used by our own app for downloads and generated blob URLs. */
const INTERNAL_PATH_HINTS = ['/downloads/', '/api/v1/'];

let installed = false;
let originalOpen = null;

function isAllowed(url) {
    if (typeof url !== 'string' || url === '') return false;

    // blob:/data: URLs are generated by our own download + player code.
    if (url.startsWith('blob:') || url.startsWith('data:')) return true;

    // Relative URLs are same-document, i.e. our own routing.
    if (url.startsWith('/') || url.startsWith('./') || url.startsWith('#')) return true;

    if (INTERNAL_PATH_HINTS.some((hint) => url.includes(hint))) return true;

    let parsed;
    try {
        parsed = new URL(url, window.location.origin);
    } catch (_) {
        return false;
    }

    const host = parsed.hostname;
    return FIRST_PARTY.some((domain) => host === domain || host.endsWith('.' + domain));
}

export function installAdShield() {
    if (installed) return () => undefined;
    if (typeof window === 'undefined' || typeof window.open !== 'function') {
        return () => undefined;
    }

    installed = true;
    originalOpen = window.open;

    window.open = function shadowStreamWindowOpen(url, target, features) {
        if (isAllowed(url)) {
            return originalOpen.call(window, url, target, features);
        }
        if (typeof console !== 'undefined') {
            console.warn('[ShadowStream AdShield] Blocked popup attempt:', url);
        }
        return null;
    };

    return uninstallAdShield;
}

export function uninstallAdShield() {
    if (!installed) return;
    window.open = originalOpen;
    originalOpen = null;
    installed = false;
}

/** Test seam: exposed so the E2E suite can assert policy without a browser click. */
export const __adShield = { isAllowed };
